// app/layout.tsx
import "./globals.css";
import React from "react";
import Link from "next/link";

export const metadata = {
  title: "Brainstorm App",
  description: "An AI-powered note-taking + web search app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <TopNav />
        <main className="flex-1 container mx-auto px-4 py-6">{children}</main>
      </body>
    </html>
  );
}

function TopNav() {
  return (
    <header className="border-b bg-white shadow-sm">
      <nav className="container mx-auto px-4 py-3 flex items-center justify-between">
        <div className="flex items-center space-x-4">
          <Link href="/" className="text-xl font-bold text-brainstorm-primary">
            Brainstorm
          </Link>
          <Link href="/notes" className="text-gray-600 hover:text-brainstorm-primary">
            Notes
          </Link>
          <Link href="/search" className="text-gray-600 hover:text-brainstorm-primary">
            Search
          </Link>
          <Link href="/bookmarks" className="text-gray-600 hover:text-brainstorm-primary">
            Bookmarks
          </Link>
        </div>
        {/* You can add a user avatar, sign out button, etc. on the right */}
      </nav>
    </header>
  );
}



// // app/layout.tsx
// import "./globals.css";
// import React from "react";

// export const metadata = {
//   title: "Brainstorm - AI-Powered Notes",
//   description: "A sleek note-taking app inspired by NotebookLM, Notion, and Perplexity",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className="flex flex-col min-h-screen">
//         <TopNav />
//         <main className="flex-1 container mx-auto px-4 py-6">{children}</main>
//       </body>
//     </html>
//   );
// }

// /**
//  * A simple top navigation bar using Tailwind
//  */
// function TopNav() {
//   return (
//     <header className="border-b bg-white">
//       <nav className="container mx-auto px-4 py-3 flex items-center justify-between">
//         <div className="flex items-center space-x-4">
//           <a href="/" className="text-xl font-bold text-brainstorm-primary">
//             Brainstorm
//           </a>
//           <a
//             href="/notes"
//             className="text-gray-600 hover:text-brainstorm-primary transition"
//           >
//             Notes
//           </a>
//         </div>

//         <div className="flex space-x-4">
//           <a
//             href="/login"
//             className="text-gray-600 hover:text-brainstorm-primary transition"
//           >
//             Log In
//           </a>
//           <a
//             href="/register"
//             className="px-3 py-1 bg-brainstorm-primary text-white rounded hover:bg-indigo-600 transition"
//           >
//             Sign Up
//           </a>
//         </div>
//       </nav>
//     </header>
//   );
// }




// // app/layout.tsx
// import React from "react";
// import "./globals.css"; // optional global CSS

// export const metadata = {
//   title: "Brainstorm App",
//   description: "AI-powered note-taking SaaS",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>
//         {children}
//       </body>
//     </html>
//   );
// }


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
